Basic Tensorflow Practice
===
Kenny Hsieh, 2018/3/16

## Constant & Variable

In [19]:
import tensorflow as tf
import numpy as np

ts_c = tf.constant(2, name = "ts_c")
ts_c

<tf.Tensor 'ts_c_1:0' shape=() dtype=int32>

In [5]:
ts_x = tf.Variable(ts_c + 5, name = "ts_x")
ts_x

<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>

## Create a Session to Calculate Computation Graph

In [6]:
sess = tf.Session()

# Inital all the tensorflow variable
init = tf.global_variables_initializer()
sess.run(init)

# Two methods to execute session
print("ts_x = ", sess.run(ts_x))
print('ts_x = ', ts_x.eval(sess))
sess.close()

('ts_x = ', 7)
('ts_x = ', 7)


In [7]:
a = tf.constant(2, name = 'a')
x = tf.Variable(a + 7, name = 'x')

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  print("a : ", sess.run(a))
  print("x : ", sess.run(x))

('a : ', 2)
('x : ', 9)


## Placeholder
- Assign value till session running

In [8]:
width = tf.placeholder("int32", name = 'width')
height = tf.placeholder("int32", name = 'height')
area = tf.multiply(width, height, name = 'area')

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  print('Area', sess.run(area, feed_dict = {width : 6, height : 8}))

('Area', 48)


In [0]:
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/area', sess.graph)

- Execute **`tensorboard --logdir=[directory_of_log_file]`**, will open the tensorboard with browser.

## Create 1, 2 Dimension Array

In [10]:
ts_x = tf.Variable([0.4, 0.2, 0.4])
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  X = sess.run(ts_x)
  print(X)
  print(X.shape)
  
ts_x = tf.Variable([[0.4, 0.2, 0.4]])
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  X = sess.run(ts_x)
  print(X)
  print(X.shape) # 1 row of data, and each data contains 3 numbers

ts_x = tf.Variable([[-0.4, 0.2, -0.4],
                  [-0.2, 0.5, -0.3],
                  [0.4, -0.3, 0.1]])
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  X = sess.run(ts_x)
  print(X)
  print(X.shape) # 3 row of data, and each data contains 3 numbers

[0.4 0.2 0.4]
(3,)
[[0.4 0.2 0.4]]
(1, 3)
[[-0.4  0.2 -0.4]
 [-0.2  0.5 -0.3]
 [ 0.4 -0.3  0.1]]
(3, 3)


## Matrix Arithmetic

In [11]:
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([[-0.5, -0.2],
                [-0.3, 0.4],
                [-0.5, 0.2]])
XW = tf.matmul(X, W)

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  X = sess.run(XW)
  print(X)
  print(X.shape)

[[-1.3  0.4]]
(1, 2)


## Simulate Neural Network

In [12]:
X = tf.Variable([[0.4, 0.2, 0.6]])
W = tf.Variable([[-0.5, -0.2],
                [-0.3, 0.4],
                [-0.5, 0.2]])
b = tf.Variable([0.1, 0.2])

XWb = tf.matmul(X, W) + b
y_r = tf.nn.relu(XWb)
y_s = tf.nn.sigmoid(XWb)

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  print('XWb : ', sess.run(XWb))
  print('Relu')
  print('y : ', sess.run(y_r))
  print('Sigmoid')
  print('y : ', sess.run(y_s))

('XWb : ', array([[-0.46000007,  0.32      ]], dtype=float32))
Relu
('y : ', array([[0.  , 0.32]], dtype=float32))
Sigmoid
('y : ', array([[0.3869858 , 0.57932425]], dtype=float32))


In [13]:
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))

XWb = tf.matmul(X, W) + b
y_r = tf.nn.relu(XWb)
y_s = tf.nn.sigmoid(XWb)

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  (_XWb, _y_r, _y_s) = sess.run((XWb, y_r, y_s))
  print('XWb : ', _XWb)
  print('Relu: ', _y_r)
  print('Sigmoid : ', _y_s)

('XWb : ', array([[-0.9093678,  1.6508255]], dtype=float32))
('Relu: ', array([[0.       , 1.6508255]], dtype=float32))
('Sigmoid : ', array([[0.28712922, 0.8390026 ]], dtype=float32))


In [23]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([1, 2]))
X = tf.placeholder("float", [None, 3])

y = tf.nn.relu(tf.matmul(X, W) + b)

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  X_array = np.array([[0.4, 0.2, 0.4]])
  (_b, _W, _X, _y) = sess.run((b, W, X, y), feed_dict = { X : X_array})
  print('b : ', _b)
  print('W : ', _W)
  print('X : ', _X)
  print('y : ', _y)

('b : ', array([[ 1.1154052 , -0.46144927]], dtype=float32))
('W : ', array([[-0.49227253, -0.58275497],
       [-0.55157626,  0.11307362],
       [-0.39860946, -0.35749352]], dtype=float32))
('X : ', array([[0.4, 0.2, 0.4]], dtype=float32))
('y : ', array([[0.64873713, 0.        ]], dtype=float32))


## Handcraft Layer Function

In [0]:
def layer(output_dim, input_dim, inputs, activation = None):
  W = tf.Variable(tf.random_normal([input_dim, output_dim]))
  b = tf.Variable(tf.random_normal([1, output_dim]))
  XWb = tf.matmul(inputs, W) + b
  
  if activation == None:
    output = XWb
  else:
    output = activation(XWb)
  return output, W, b

In [34]:
X = tf.placeholder("float32", [None, 4])

h, W1, b1 = layer(3, 4, X, tf.nn.relu)
y, W2, b2 = layer(2, 3, h)

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  sess.run(init)
  
  X_array = np.array([[0.4, 0.2, 0.4, 0.5]])
  (layer_X, layer_h, layer_y, W1, b1, W2, b2) = sess.run((X, h, y, W1, b1, W2, b2), feed_dict = {X : X_array})
  
  print('Input Layer : ', layer_X)
  print('W1 : ', W1, ', b1 : ', b1)
  print('Hidden Layer : ', layer_h)
  print('W2 : ', W2, ', b2 : ', b2)
  print('Output Layer : ', layer_y)

('Input Layer : ', array([[0.4, 0.2, 0.4, 0.5]], dtype=float32))
('W1 : ', array([[ 0.69587064,  0.6382746 , -2.5772066 ],
       [-0.22341587,  0.8080179 , -0.4564998 ],
       [-0.24313585, -0.6282256 , -0.37795904],
       [-1.3730637 ,  0.8430222 ,  0.11227571]], dtype=float32), ', b1 : ', array([[ 0.57537514, -2.1655915 ,  1.9436853 ]], dtype=float32))
('Hidden Layer : ', array([[0.02525407, 0.        , 0.72645676]], dtype=float32))
('W2 : ', array([[-1.3971837,  0.1686633],
       [-1.9247552, -1.1574886],
       [-0.4023703,  1.8594106]], dtype=float32), ', b2 : ', array([[-0.01438231,  0.2864378 ]], dtype=float32))
('Output Layer : ', array([[-0.34197152,  1.6414788 ]], dtype=float32))
